### ISSUE TITLE
Rethink issue labels and convential commit types

### ISSUE THREAD

**Issue by redeboer** [ComPWA/.github#7]
See [Commit conventions](https://compwa-org.readthedocs.io/develop.html#commit-conventions) and [ComPWA repository labels](https://github.com/organizations/ComPWA/settings/repository-defaults).

- There is a mismatch between the [headers of the release drafter](https://github.com/ComPWA/repo-maintenance/blob/0cb2b3f4fdff6d3bcda1c87b5ea326e6f070ff93/.github/release-drafter.yml).
- Commits that introduce **interface changes** should become easier to identify. [Conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/#specification) `refactor` and `chore` are too ambiguous.
- Conventional commit type `ci` is collecting many meanings since 'local' CI, GitHub Actions, and deployment have become more synchronised (through `tox`).
- The DX and Maintenance labels are also ambiguous.

Need at least labels for:
- **Interface changes**: scripts that use this library may need to be modified.
- **Behaviour changes**: same interface, but can output can be affected. Example: https://github.com/ComPWA/ampform/pull/270.
- **New features** or **enhancements**. It might be an idea to distinguish between additions to the interface (new features) and performance improvements (enhancement).
- **Maintenance**: refactoring that does not affect behaviour or interface.
- Improvements to the **Developer Experience**: some new features that make it easier to develop the framework. These include local improvements as well as improvements to CI and CD.
- **Documentation**: changes that apply purely to the `docs` folder, to docstrings in the source code, or to any other explanatory files.

**Comment by spflueger** [comment]
Angular conventional commit messages have "breaking change" as an additonal marker independent of the commit type https://www.conventionalcommits.org/en/v1.0.0/#summary
